### ISSUE TITLE
Can MigrationCommand be a Semigroup?

### ISSUE THREAD

**Issue by expipiplus1** [ameingast/postgresql-simple-migration#13]
Would it make sense to add another constructor to `MigrationCommand`. This constructor would be `MigrationCommands :: [MigrationCommand] -> MigrationCommand`. This would represent a sequence of commands to run one after another.

**Comment by ameingast** [comment]
What's a practical use case for this? 

I'm asking, because the error semantics for executing a sequence of ```MigrationCommand```s are not obvious. E.g., what happens when you run the sequence ```[MigrationInitialization, MigrationFile, MigrationDirectory]``` and the execution blows up during ```MigrationFile```? Is the initialisation rolled back? Do we need to execute the sequence in a database transaction? etc

**Comment by expipiplus1** [comment]
postgresql-simple-migration seems to leave the transaction handling up to the user. I'd expect things to be rolled back if the user has wrapped things in a transaction.

I'd expect it to work as though all the commands were written out to files in a directory and `MigrationDirectory` was called there. `MigrationDirectory` is already a way of running a sequence of commands.

**Comment by ameingast** [comment]
Alright, if you can come up with a solution I'll have a look and merge it in.

**Comment by expipiplus1** [comment]
Thanks!
