### ISSUE TITLE
More verbosity would help track script issues

### ISSUE THREAD

**Issue by adfretlink** [ameingast/postgresql-simple-migration#22]
Currently, errors on running script will get you a pretty printed sql exception, which is nice. However, the particular query that failed is not printed, nor the script that was run. I'd be more than happy to write a PR to display these in case of error, if that's ok with you.

**Comment by ameingast** [comment]
Absolutely! Thanks for contributing!

**Comment by adfretlink** [comment]
Sorry for the delay, I had less time to contribute that I hoped for. Here's a PR with my solution to this problem: https://github.com/ameingast/postgresql-simple-migration/pull/23

**Comment by ameingast** [comment]
Sorry this took so long, but I'm not merging this, because the changes could potentially break existing deployments. 

The solution would work if it was a complete (Postgres) SQL parser that properly separates statements. I'm not confident that this solution can handle all complex SQL statements. 

A workaround for your issue would be to split up SQL statements into separate files.
